### ISSUE TITLE
Error: Cannot find module tslib

### ISSUE THREAD

**Issue by Delta-official** [LinaTsukusu/youtube-chat#13]
The code displays an error that says `Cannot find module tslib` when trying to run the script. I've tried running `npm install` in the `youtube-chat` directory, but it did nothing.

I am not entirely sure what causes the error because after inspection of `youtube-chat`'s source code it seems that everything is fine.

Error in question:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- /Users/Delta/Desktop/Projects/RealProjects/js-projects/Rigel_js/node_modules/youtube-chat/dist/live-chat.js
- /Users/Delta/Desktop/Projects/RealProjects/js-projects/Rigel_js/node_modules/youtube-chat/dist/index.js
- /Users/Delta/Desktop/Projects/RealProjects/js-projects/Rigel_js/Interpreter.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/Delta/Desktop/Projects/RealProjects/js-projects/Rigel_js/node_modules/youtube-chat/dist/live-chat.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/Delta/Desktop/Projects/RealProjects/js-projects/Rigel_js/node_modules/youtube-chat/dist/live-chat.js',
    '/Users/Delta/Desktop/Projects/RealProjects/js-projects/Rigel_js/node_modules/youtube-chat/dist/index.js',
    '/Users/Delta/Desktop/Projects/RealProjects/js-projects/Rigel_js/Interpreter.js'
  ]
}
```

**Comment by Chipsnet** [comment]
Do `yarn add tslib` and resolve dependencies
(if you using npm, you must do `npm install tslib`
