### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by fu-raz** [LinaTsukusu/youtube-chat#69]
I'm getting this error quite a lot when I use the Youtube-Chat package. Then after a few restarts of the script it works again. Any idea what's causing this?

```
TypeError: Cannot read properties of undefined (reading '0')
    at C:\Development\nodejs\youtube-chat\node_modules\youtube-chat\dist\parser.js:97:49
    at Array.map (<anonymous>)
    at parseMessages (C:\Development\nodejs\youtube-chat\node_modules\youtube-chat\dist\parser.js:89:17)      
    at parseActionToChatItem (C:\Development\nodejs\youtube-chat\node_modules\youtube-chat\dist\parser.js:148:18)
    at C:\Development\nodejs\youtube-chat\node_modules\youtube-chat\dist\parser.js:54:25
    at Array.map (<anonymous>)
    at parseChatData (C:\Development\nodejs\youtube-chat\node_modules\youtube-chat\dist\parser.js:54:14)      
    at C:\Development\nodejs\youtube-chat\node_modules\youtube-chat\dist\requests.js:30:43
    at Generator.next (<anonymous>)
    at fulfilled (C:\Development\nodejs\youtube-chat\node_modules\youtube-chat\dist\requests.js:5:58)

```

**Comment by MakerDockio** [comment]
@neverclear86 Getting the same issue and @fu-raz above seems there is a parsing issue, are you able to point us in the right direction for a fix please.

**Comment by eduardobento** [comment]
Temporary soluction:

Parser.js line 97, change to:

`const shortcut = (run.emoji?.shortcuts?.length > 0) ? run.emoji?.shortcuts[0] : "";`

**Comment by rodrigograca31** [comment]
same here when using a `liveId` to start reading the chat. not when using `channelId`
