### ISSUE TITLE
Issue with emojis

### ISSUE THREAD

**Issue by iamllama** [LinaTsukusu/youtube-chat#74]
Keep getting these exceptions, think the code for handling emojis' got obsoleted?

`TypeError: Cannot read properties of undefined (reading '0')
    at /home/projects/aussiebot/node_modules/youtube-chat/dist/parser.js:97:45
    at Array.map (<anonymous>)
    at parseMessages (/home/projects/node_modules/youtube-chat/dist/parser.js:89:15)
    at parseActionToChatItem (/home/projects/node_modules/youtube-chat/dist/parser.js:148:14)
    at /home/projects/node_modules/youtube-chat/dist/parser.js:54:19
    at Array.map (<anonymous>)
    at parseChatData (/home/projects/node_modules/youtube-chat/dist/parser.js:54:8)
    at /home/projects/aussiebot/node_modules/youtube-chat/dist/requests.js:30:43
    at Generator.next (<anonymous>)
    at fulfilled (/home/projects/node_modules/youtube-chat/dist/requests.js:5:58)`

Temporarily 'fixed' it adding return `null`  i.e
`else {
      // Emoji
      return null;
      const thumbnail = run.emoji.image.thumbnails.shift();
      const isCustomEmoji = Boolean(run.emoji.isCustomEmoji);
      const shortcut = run?.emoji?.shortcuts[0];
      return {
        url: thumbnail ? thumbnail.url : "",
        alt: shortcut,
        isCustomEmoji: isCustomEmoji,
        emojiText: isCustomEmoji ? shortcut : run.emoji.emojiId,
      };
    }`

**Comment by iamllama** [comment]
Found an emoji which causes this error to appear: 🙌🏾

**Comment by neverclear86** [comment]
Closed because it was merged 🎉
